#use_frameworks!
source 'https://gitee.com/wowbby/repo.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'EYNetworkClient_Example' do
  pod 'EYNetworkClient', :path => '../'

  target 'EYNetworkClient_Tests' do
    inherit! :search_paths

    
  end
end
